name: Releases

on:
  push:
    tags:
    - '*'

jobs:
  deployment:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build jami
        env:
          RELEASE_VERSION: ${{ github.ref_name }}
        run: |
          cd jami-android && ./gradlew --no-daemon app:assembleWithUnifiedPushRelease -Parchs=armeabi-v7a,arm64-v8a

      - uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          removeArtifacts: false
          replacesArtifacts: false
          artifacts: jami-android/app/build/outputs/apk/withUnifiedPush/release/app-withUnifiedPush-release.apk
